version: "3.8"
services:
    nodeserver:
      build:
          context: ./siska1
      ports:
          - "5000:5000"
    nginx:
      restart: always
      build:
          context: ./siska1/nginx
      ports:
          - "80:80"